name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main' branch

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest  # Run tests on an Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q  # Run the tests

  # Job to deploy the FastAPI app
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure the tests pass before deploying

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code again

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      # Add deployment step (for example, to a server)
      - name: Deploy FastAPI app
        run: |
          echo "Deploying FastAPI app to server"
          # Example of deployment (adjust the script as per your environment)
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /path/to/your/app &&
            git pull origin main &&
            pip install -r requirements.txt &&
            pm2 restart fastapi-app
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Set the private SSH key for authentication
